//
//  IRAFileSystem.h
//  TestObject
//
//  Created by 冯驰伟 on 2019/1/1.
//  Copyright © 2019 冯驰伟. All rights reserved.
//

// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from IFileService.djinni

@protocol IRAFileSystem <NSObject>


@end

